<a href="https://colab.research.google.com/github/hrai/pytorch-tutorials/blob/master/Autograd_Automatic_Differentiation.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

## Tensor

In [0]:
import torch


In [28]:
x=torch.ones(2,2, requires_grad=True)
print(x)

tensor([[1., 1.],
        [1., 1.]], requires_grad=True)


In [29]:
y=x+2
print(y)

tensor([[3., 3.],
        [3., 3.]], grad_fn=<AddBackward0>)


In [30]:
print(y.grad_fn)

In [31]:
z=y*y*3
out=z.mean()
print(z,out)

tensor([[27., 27.],
        [27., 27.]], grad_fn=<MulBackward0>) tensor(27., grad_fn=<MeanBackward0>)


In [32]:
a=torch.randn(2,2)
a=((a*3)/(a-1))
print(a.requires_grad)
a.requires_grad_(True)
print(a.requires_grad)
b=(a*a).sum()
print(b.grad_fn)

False
True


## Gradients

In [33]:
out.backward()
print(x.grad)

tensor([[4.5000, 4.5000],
        [4.5000, 4.5000]])


In [35]:
x=torch.randn(3, requires_grad=True)
y=x*2
while y.data.norm() < 1000:
    print(y)
    y=y*2

print(y)

tensor([ 1.0219, -1.0492, -2.4217], grad_fn=<MulBackward0>)
tensor([ 2.0438, -2.0985, -4.8434], grad_fn=<MulBackward0>)
tensor([ 4.0876, -4.1970, -9.6869], grad_fn=<MulBackward0>)
tensor([  8.1753,  -8.3939, -19.3738], grad_fn=<MulBackward0>)
tensor([ 16.3505, -16.7879, -38.7475], grad_fn=<MulBackward0>)
tensor([ 32.7011, -33.5757, -77.4951], grad_fn=<MulBackward0>)
tensor([  65.4021,  -67.1514, -154.9902], grad_fn=<MulBackward0>)
tensor([ 130.8043, -134.3029, -309.9803], grad_fn=<MulBackward0>)
tensor([ 261.6085, -268.6057, -619.9606], grad_fn=<MulBackward0>)
tensor([  523.2170,  -537.2115, -1239.9213], grad_fn=<MulBackward0>)


In [36]:
v=torch.tensor([0.1,1.0,0.0001], dtype=torch.float)
y.backward(v)

print(x.grad)

tensor([1.0240e+02, 1.0240e+03, 1.0240e-01])


In [38]:
print(x.requires_grad)
print((x*x).requires_grad)

with torch.no_grad():
    print((x**2).requires_grad)

True
True
False


In [39]:
print(x.requires_grad)
y=x.detach()
print(y.requires_grad)
print(x.eq(y).all())

True
False
tensor(True)
