<a href="https://colab.research.google.com/github/hrai/pytorch-tutorials/blob/master/PyTorch_tutorial.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [0]:
from __future__ import print_function
import torch


In [0]:
x=torch.empty(5,3)
print(x)

tensor([[1.4282e-36, 0.0000e+00, 0.0000e+00],
        [0.0000e+00, 0.0000e+00, 0.0000e+00],
        [0.0000e+00, 0.0000e+00, 2.8026e-45],
        [0.0000e+00, 1.1210e-44, 0.0000e+00],
        [1.4013e-45, 0.0000e+00, 0.0000e+00]])


In [0]:
x=torch.rand(5,3)
print(x)

tensor([[0.5565, 0.5548, 0.5167],
        [0.3074, 0.7684, 0.6417],
        [0.2157, 0.6598, 0.4639],
        [0.6564, 0.5068, 0.5358],
        [0.9535, 0.8486, 0.4241]])


In [0]:
x=torch.zeros(5,3, dtype=torch.long)
x

tensor([[0, 0, 0],
        [0, 0, 0],
        [0, 0, 0],
        [0, 0, 0],
        [0, 0, 0]])

In [0]:
x = torch.tensor([5.5, 3])
print(x)

tensor([5.5000, 3.0000])


In [0]:
x=x.new_ones(5,3,dtype=torch.double)
print(x)

x=torch.randn_like(x, dtype=torch.float)
print(x)

tensor([[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]], dtype=torch.float64)
tensor([[-0.2461,  1.9758,  0.4354],
        [-0.9924,  0.6891,  1.1185],
        [-0.6321,  0.4243, -0.2057],
        [ 2.0096, -0.9440, -0.3159],
        [ 1.1081, -2.3719, -1.0901]])


In [0]:
print(x.size())

torch.Size([5, 3])


In [0]:
y=torch.rand(5,3)
print(x+y)

tensor([[ 0.2645,  2.3954,  1.2267],
        [-0.5257,  1.6057,  1.4925],
        [ 0.0291,  0.6277, -0.1776],
        [ 2.9051, -0.2707,  0.5709],
        [ 1.3325, -2.3134, -0.7653]])


In [0]:
print(torch.add(x,y))

tensor([[ 0.2645,  2.3954,  1.2267],
        [-0.5257,  1.6057,  1.4925],
        [ 0.0291,  0.6277, -0.1776],
        [ 2.9051, -0.2707,  0.5709],
        [ 1.3325, -2.3134, -0.7653]])


In [0]:
result=torch.empty(5,3)
torch.add(x,y,out=result)
print(result)

tensor([[ 0.2645,  2.3954,  1.2267],
        [-0.5257,  1.6057,  1.4925],
        [ 0.0291,  0.6277, -0.1776],
        [ 2.9051, -0.2707,  0.5709],
        [ 1.3325, -2.3134, -0.7653]])


In [0]:
y.add_(x)
print(y)

tensor([[ 0.2645,  2.3954,  1.2267],
        [-0.5257,  1.6057,  1.4925],
        [ 0.0291,  0.6277, -0.1776],
        [ 2.9051, -0.2707,  0.5709],
        [ 1.3325, -2.3134, -0.7653]])
