<a href="https://colab.research.google.com/github/hrai/pytorch-tutorials/blob/master/PyTorch_tutorial.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

## PyTorch Basics


In [0]:
from __future__ import print_function
import torch


In [3]:
x=torch.empty(5,3)
print(x)

tensor([[9.0570e-37, 0.0000e+00, 0.0000e+00],
        [0.0000e+00, 0.0000e+00, 0.0000e+00],
        [0.0000e+00, 0.0000e+00, 2.8026e-45],
        [0.0000e+00, 1.1210e-44, 0.0000e+00],
        [1.4013e-45, 0.0000e+00, 1.0501e-25]])


In [4]:
x=torch.rand(5,3)
print(x)

tensor([[0.3658, 0.6194, 0.2627],
        [0.7649, 0.5937, 0.7930],
        [0.8612, 0.0777, 0.3440],
        [0.1769, 0.7277, 0.1262],
        [0.9522, 0.2455, 0.0201]])


In [5]:
x=torch.zeros(5,3, dtype=torch.long)
x

tensor([[0, 0, 0],
        [0, 0, 0],
        [0, 0, 0],
        [0, 0, 0],
        [0, 0, 0]])

In [6]:
x = torch.tensor([5.5, 3])
print(x)

tensor([5.5000, 3.0000])


In [7]:
x=x.new_ones(5,3,dtype=torch.double)
print(x)

x=torch.randn_like(x, dtype=torch.float)
print(x)

tensor([[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]], dtype=torch.float64)
tensor([[ 1.5648, -0.2098,  0.8689],
        [-2.2293, -0.8930, -0.2142],
        [-0.6160,  1.1673,  0.4789],
        [-1.2000, -0.1970, -0.5001],
        [ 1.3269, -1.2191, -0.7736]])


In [8]:
print(x.size())

torch.Size([5, 3])


In [9]:
y=torch.rand(5,3)
print(x+y)

tensor([[ 2.3395,  0.3711,  1.1676],
        [-1.5820, -0.4773, -0.1391],
        [ 0.1995,  1.7604,  0.5619],
        [-0.5377,  0.6220, -0.2411],
        [ 1.7990, -0.6232,  0.1633]])


In [10]:
print(torch.add(x,y))

tensor([[ 2.3395,  0.3711,  1.1676],
        [-1.5820, -0.4773, -0.1391],
        [ 0.1995,  1.7604,  0.5619],
        [-0.5377,  0.6220, -0.2411],
        [ 1.7990, -0.6232,  0.1633]])


In [11]:
result=torch.empty(5,3)
torch.add(x,y,out=result)
print(result)

tensor([[ 2.3395,  0.3711,  1.1676],
        [-1.5820, -0.4773, -0.1391],
        [ 0.1995,  1.7604,  0.5619],
        [-0.5377,  0.6220, -0.2411],
        [ 1.7990, -0.6232,  0.1633]])


In [12]:
y.add_(x)
print(y)

tensor([[ 2.3395,  0.3711,  1.1676],
        [-1.5820, -0.4773, -0.1391],
        [ 0.1995,  1.7604,  0.5619],
        [-0.5377,  0.6220, -0.2411],
        [ 1.7990, -0.6232,  0.1633]])


In [27]:
print(x)
print(x[:,2])

print(x[2,:])

tensor([[ 1.5648, -0.2098,  0.8689],
        [-2.2293, -0.8930, -0.2142],
        [-0.6160,  1.1673,  0.4789],
        [-1.2000, -0.1970, -0.5001],
        [ 1.3269, -1.2191, -0.7736]])
tensor([ 0.8689, -0.2142,  0.4789, -0.5001, -0.7736])
tensor([-0.6160,  1.1673,  0.4789])


In [28]:
x=torch.randn(4,4)
y=x.view(16)
z=x.view(-1,8)
print(x.size(),y.size(),z.size())

torch.Size([4, 4]) torch.Size([16]) torch.Size([2, 8])


In [31]:
print(x)
print(y)

tensor([[-0.9339,  0.8805,  1.8538,  0.7031],
        [ 1.3926, -0.7867, -0.5836,  2.7452],
        [ 1.7984, -1.4433,  0.6452,  1.9542],
        [-2.1321,  2.5977, -2.4721,  0.2587]])
tensor([-0.9339,  0.8805,  1.8538,  0.7031,  1.3926, -0.7867, -0.5836,  2.7452,
         1.7984, -1.4433,  0.6452,  1.9542, -2.1321,  2.5977, -2.4721,  0.2587])


In [32]:
x=torch.randn(1)
print(x)
print(x.item())

tensor([0.8179])
0.8179216980934143


## NumPy bridge